require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OoglersController do

  # This should return the minimal set of attributes required to create a valid
  # Oogler. As you add validations to Oogler, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OoglersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ooglers as @ooglers" do
      oogler = Oogler.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ooglers).should eq([oogler])
    end
  end

  describe "GET show" do
    it "assigns the requested oogler as @oogler" do
      oogler = Oogler.create! valid_attributes
      get :show, {:id => oogler.to_param}, valid_session
      assigns(:oogler).should eq(oogler)
    end
  end

  describe "GET new" do
    it "assigns a new oogler as @oogler" do
      get :new, {}, valid_session
      assigns(:oogler).should be_a_new(Oogler)
    end
  end

  describe "GET edit" do
    it "assigns the requested oogler as @oogler" do
      oogler = Oogler.create! valid_attributes
      get :edit, {:id => oogler.to_param}, valid_session
      assigns(:oogler).should eq(oogler)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Oogler" do
        expect {
          post :create, {:oogler => valid_attributes}, valid_session
        }.to change(Oogler, :count).by(1)
      end

      it "assigns a newly created oogler as @oogler" do
        post :create, {:oogler => valid_attributes}, valid_session
        assigns(:oogler).should be_a(Oogler)
        assigns(:oogler).should be_persisted
      end

      it "redirects to the created oogler" do
        post :create, {:oogler => valid_attributes}, valid_session
        response.should redirect_to(Oogler.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved oogler as @oogler" do
        # Trigger the behavior that occurs when invalid params are submitted
        Oogler.any_instance.stub(:save).and_return(false)
        post :create, {:oogler => {}}, valid_session
        assigns(:oogler).should be_a_new(Oogler)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Oogler.any_instance.stub(:save).and_return(false)
        post :create, {:oogler => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested oogler" do
        oogler = Oogler.create! valid_attributes
        # Assuming there are no other ooglers in the database, this
        # specifies that the Oogler created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Oogler.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => oogler.to_param, :oogler => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested oogler as @oogler" do
        oogler = Oogler.create! valid_attributes
        put :update, {:id => oogler.to_param, :oogler => valid_attributes}, valid_session
        assigns(:oogler).should eq(oogler)
      end

      it "redirects to the oogler" do
        oogler = Oogler.create! valid_attributes
        put :update, {:id => oogler.to_param, :oogler => valid_attributes}, valid_session
        response.should redirect_to(oogler)
      end
    end

    describe "with invalid params" do
      it "assigns the oogler as @oogler" do
        oogler = Oogler.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Oogler.any_instance.stub(:save).and_return(false)
        put :update, {:id => oogler.to_param, :oogler => {}}, valid_session
        assigns(:oogler).should eq(oogler)
      end

      it "re-renders the 'edit' template" do
        oogler = Oogler.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Oogler.any_instance.stub(:save).and_return(false)
        put :update, {:id => oogler.to_param, :oogler => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested oogler" do
      oogler = Oogler.create! valid_attributes
      expect {
        delete :destroy, {:id => oogler.to_param}, valid_session
      }.to change(Oogler, :count).by(-1)
    end

    it "redirects to the ooglers list" do
      oogler = Oogler.create! valid_attributes
      delete :destroy, {:id => oogler.to_param}, valid_session
      response.should redirect_to(ooglers_url)
    end
  end

end
