require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PreviousAddressesController do

  # This should return the minimal set of attributes required to create a valid
  # PreviousAddress. As you add validations to PreviousAddress, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PreviousAddressesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all previous_addresses as @previous_addresses" do
      previous_address = PreviousAddress.create! valid_attributes
      get :index, {}, valid_session
      assigns(:previous_addresses).should eq([previous_address])
    end
  end

  describe "GET show" do
    it "assigns the requested previous_address as @previous_address" do
      previous_address = PreviousAddress.create! valid_attributes
      get :show, {:id => previous_address.to_param}, valid_session
      assigns(:previous_address).should eq(previous_address)
    end
  end

  describe "GET new" do
    it "assigns a new previous_address as @previous_address" do
      get :new, {}, valid_session
      assigns(:previous_address).should be_a_new(PreviousAddress)
    end
  end

  describe "GET edit" do
    it "assigns the requested previous_address as @previous_address" do
      previous_address = PreviousAddress.create! valid_attributes
      get :edit, {:id => previous_address.to_param}, valid_session
      assigns(:previous_address).should eq(previous_address)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PreviousAddress" do
        expect {
          post :create, {:previous_address => valid_attributes}, valid_session
        }.to change(PreviousAddress, :count).by(1)
      end

      it "assigns a newly created previous_address as @previous_address" do
        post :create, {:previous_address => valid_attributes}, valid_session
        assigns(:previous_address).should be_a(PreviousAddress)
        assigns(:previous_address).should be_persisted
      end

      it "redirects to the created previous_address" do
        post :create, {:previous_address => valid_attributes}, valid_session
        response.should redirect_to(PreviousAddress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved previous_address as @previous_address" do
        # Trigger the behavior that occurs when invalid params are submitted
        PreviousAddress.any_instance.stub(:save).and_return(false)
        post :create, {:previous_address => {}}, valid_session
        assigns(:previous_address).should be_a_new(PreviousAddress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PreviousAddress.any_instance.stub(:save).and_return(false)
        post :create, {:previous_address => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested previous_address" do
        previous_address = PreviousAddress.create! valid_attributes
        # Assuming there are no other previous_addresses in the database, this
        # specifies that the PreviousAddress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PreviousAddress.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => previous_address.to_param, :previous_address => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested previous_address as @previous_address" do
        previous_address = PreviousAddress.create! valid_attributes
        put :update, {:id => previous_address.to_param, :previous_address => valid_attributes}, valid_session
        assigns(:previous_address).should eq(previous_address)
      end

      it "redirects to the previous_address" do
        previous_address = PreviousAddress.create! valid_attributes
        put :update, {:id => previous_address.to_param, :previous_address => valid_attributes}, valid_session
        response.should redirect_to(previous_address)
      end
    end

    describe "with invalid params" do
      it "assigns the previous_address as @previous_address" do
        previous_address = PreviousAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PreviousAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => previous_address.to_param, :previous_address => {}}, valid_session
        assigns(:previous_address).should eq(previous_address)
      end

      it "re-renders the 'edit' template" do
        previous_address = PreviousAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PreviousAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => previous_address.to_param, :previous_address => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested previous_address" do
      previous_address = PreviousAddress.create! valid_attributes
      expect {
        delete :destroy, {:id => previous_address.to_param}, valid_session
      }.to change(PreviousAddress, :count).by(-1)
    end

    it "redirects to the previous_addresses list" do
      previous_address = PreviousAddress.create! valid_attributes
      delete :destroy, {:id => previous_address.to_param}, valid_session
      response.should redirect_to(previous_addresses_url)
    end
  end

end
